apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: udp-collector
  name: udp-collector
  namespace: occ
spec:
  externalTrafficPolicy: Local
  ports:
  - name: udp-traffic
    nodePort: 30400
    port: 4739
    protocol: UDP
    targetPort: 4739
  selector:
    app.kubernetes.io/instance: udp-collector
    app.kubernetes.io/name: udp-collector
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}